queue_rules:
  - name: default
    merge_method: squash

pull_request_rules:
  - name: automatic merge for upstream skills sync
    conditions:
      - head = sync-upstream-skills
      - label = automated-sync
    actions:
      queue:
        name: default
