version = 1

[[sources]]
repo = "Mic92/mics-skills"
commit = "1e6eef8e989bf5d88bfa9ca29b50a472df795927"

[[sources]]
repo = "mattpocock/skills"
commit = "c55ee46073ed923f86ce59a5eb3b6d895095d1b7"

[[sources]]
repo = "longbridge/gpui-kit"
commit = "f8cd486005ab1c09fd6cf9fc00e8a4ca42a4ad17"

[[sources]]
repo = "Leonxlnx/taste-skill"
commit = "ce26fc25c0e5e8cab638f883de62d9a86ee5e45b"
